services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx/
        ports:
        - "443:443"
        restart: on-failure
        depends_on: 
          - wordpress
        networks: 
          - inception
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb/
        env_file: .env
        restart: on-failure
        networks: 
          - inception
        expose:
          - "3306"
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress/
        restart: on-failure
        depends_on: 
          - mariadb
        networks: 
          - inception
        expose:
          - "9000"
networks:
    inception:
        driver: bridge