services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx/
        ports:
        - "443:443"
        restart: on-failure
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb/
        env_file: .env
        restart: on-failure
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress/
        restart: on-failure